---
- name: execute script and get result back.
  hosts: 169.57.13.100
  #vars: 
      #threshold: 50
  tasks:
    - name: Execute the script
      shell: sh /root/eca/dr1.sh
      failed_when: false
      register: mypass
    - name: Print the script result
      debug:
        msg: "{{ mypass }}"
      #when: mypass.stdout | regex_search('Breached')
    #- meta: end_play
      
        
      
    #- set_fact:
        #my_var: "{{ mypass.stdout | regex_search('([0-9]+[%])')}}"

    #- name: Print value
      #debug:
        #var: my_var
        
    - name: To ping to Slack to send message
      slack:
         token: T4W1S5P34/B02MEUC40E9/iBeMJQKNdwG67tu90pxlPXGZ
         domain: hooks.slack.com
         channel: '#ansible_eca_test'
         msg: "{{ mypass.stdout }}"
      #when: mypass.stdout.findint > 40
      when: mypass.stdout >= "90"
      
      #when: mypass.stdout | regex_search('Breached')
      

      
