---
- name: execute script and get result back.
  hosts: 169.57.13.100
  vars: 
      threshold: 20
  tasks:
    - name: Execute the script
      shell: sh /root/eca/dr1.sh
      failed_when: false
      register: mypass
    - name: Print the script result
      debug:
        msg: "{{ mypass.stdout }}"
        
    - name: Launch a Workflow with parameters without waiting
      tower_workflow_launch:
        workflow_template: "dr Test git new workflow"
        #extra_vars: "---
    #my: "{{ mypass.stdout }}"
        #wait: False
      delegate_to: localhost
      run_once: true
      register: workflow_task_info
        
      
    #- set_fact:
    #    my_var: "{{ mypass.stdout | regex_search('([0-9]+)')}}"

    #- name: Print value
    # debug:
    #   var: my_var
        
    - name: To ping to Slack to send message
      slack:
         token: T4W1S5P34/B02MEUC40E9/Wmjqqy30hENvhsa3bqLfddcZ
         domain: hooks.slack.com
         channel: '#ansible_eca_test'
         msg: "{{mypass.stdout}}"
      #when: (my_var | int) >= {{threshold}}
