---
- name: execute script and get result back.
  hosts: 169.57.13.100
  vars: 
      threshold: 20
  tasks:
    - name: Execute the script
      shell: sh /root/eca/dr1.sh
      failed_when: false
      register: mypass
    - name: Print the script result
      debug:
        msg: "{{ mypass.stdout }}"
        
    - set_fact:
        my_var: "{{ mypass.stdout | regex_search('Breached')}}"

    - name: Print
      debug:
        var: my_var
        msg: "{{ my_var.stdout }}"
        
      
    #- set_fact:
    #    my_var: "{{ mypass.stdout | regex_search('([0-9]+)')}}"

    #- name: Print value
    # debug:
    #   var: my_var
        
    - name: To ping to Slack to send message
      slack:
         token: T4W1S5P34/B02MEUC40E9/Wmjqqy30hENvhsa3bqLfddcZ
         domain: hooks.slack.com
         channel: '#ansible_eca_test'
         msg: "{{my_var.stdout}}"
      #when: (my_var | int) >= {{threshold}}
